# Generated by Django 4.0.3 on 2022-04-20 05:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de los estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nombreCompleto', models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo')),
                ('tipo', models.CharField(choices=[('0', 'Nivelación'), ('1', 'Pregrado'), ('2', 'Maestría'), ('3', 'Doctorado')], max_length=1, verbose_name='Tipo')),
                ('cartaMotivacion', ckeditor.fields.RichTextField()),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.facultad')),
                ('habilidad', models.ManyToManyField(to='persona.habilidades')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes matriculados',
                'ordering': ['id'],
            },
        ),
    ]
