# Generated by Django 4.0.3 on 2022-04-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultad',
            options={'ordering': ['id'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Nuestras Facultades'},
        ),
    ]
